### ISSUE TITLE
What to change for Fahrenheit?

### ISSUE THREAD

**Issue by jcf6288** [mhaack/mqtt-bme280-homie#5]
Can anyone assist me in displaying temperature in Fahrenheit?

**Comment by luebbe** [comment]
http://lmgtfy.com/?q=conversion+fahrenheit+celsius ;)

**Comment by mhaack** [comment]
And then adapt https://github.com/mhaack/mqtt-bme280-homie/blob/master/src/BME280Node.cpp#L40 and https://github.com/mhaack/mqtt-bme280-homie/blob/master/src/BME280Node.cpp#L48

**Comment by jcf6288** [comment]
Thanks now that should be doable with my limited coding skills.

**Comment by jcf6288** [comment]
Do I have to changed anything in the images.h file for the display?

**Comment by mhaack** [comment]
No, only this line
https://github.com/mhaack/mqtt-bme280-homie/blob/master/src/mqtt-gateway-bme280.cpp#L67
which displays °C needs to be changed.
